sonar.projectKey=datevscm_encounter-your-doom
sonar.projectName=encounter-your-doom
sonar.organization=datevscm

sonar.qualitygate.wait=true

# source code
sonar.sources=src/main,pom.xml
sonar.java.binaries=target/classes
sonar.exclusions=**/application.yml

# test code
sonar.tests=src/test

# code coverage
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
