spring.application.name=encounter-your-doom
spring.data.mongodb.uri=mongodb://d8567fb-mongodb-0.node.dc1.consul.a9s.dev:27017
spring.data.mongodb.database=mongodb
spring.data.mongodb.username=a9s-brk-usr-34102acf5ce411232541d7bfad6a1fc60b84e400
spring.data.mongodb.password=a9s28f42a9728fe145caa325e92a2af391e95bd563c
spring.threads.virtual.enabled=true
