spring.application.name=encounter-your-doom
#spring.data.mongodb.uri=mongodb://localhost:27017/
spring.data.mongodb.uri=mongodb://a9s-brk-usr-faf7d181f61f4946004b0acaa61ccf711a43dc79:a9sea78205dd84465e3101076dd887431b79c7d220e@d8567fb-mongodb-0.node.dc1.consul.a9s.dev:27017/d8567fb?ssl=true"
spring.data.mongodb.database=mongodb
spring.threads.virtual.enabled=true

de.flapdoodle.mongodb.embedded.version=7.0.5
