spring.application.name=encounter-your-doom
#spring.data.mongodb.uri=${vcap.services.mongodb.mongo\DBServiceKey.credentials.uri}
#spring.data.mongodb.database=mongodb
#spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb://localhost:27017/test
spring.data.mongodb.uuid-representation=standard
spring.data.mongodb.database=DnD
