# =============================================================================
# 📦 This workflow is part of DATEV's modular GitHub Flow:
#
# Version: v1.9.0
# File on Github: https://github.com/datevscm/progressive-workflows/blob/v1.9.0/pre-designed-workflows/github-flow/maven-app/publish.yml
# Releases: https://github.com/datevscm/progressive-workflows/releases
#
# 📚 Helpful documentation
# Big Picture: https://confluence.datev.de/x/a8WAJ
# Artifactory Doc: https://github.com/datevscm/progressive-workflows/blob/v1.9.0/pre-designed-workflows/github-flow/docs/artifactory.md
# Deploy Key Doc: https://github.com/datevscm/progressive-workflows/blob/v1.9.0/pre-designed-workflows/github-flow/docs/deploy_key.md
# Vault Doc: https://github.com/datevscm/progressive-workflows/blob/v1.9.0/pre-designed-workflows/github-flow/docs/vault.md
# =============================================================================

name: Publish
run-name: Publish ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      version-bump:
        type: choice
        description: "Version section to bump"
        options:
          - major
          - minor
          - patch
        default: patch
  pull_request:
    types:
      - closed
    branches:
      - main # ProFlows-Setup-TODO [YOUR_DEFAULT_BRANCH_NAME] replace with your default branch name

env:
  VERSION_BUMP: ${{ github.event.inputs.version-bump || 'minor' }}
  # =================== If Vault is used ==========================
  #  JF_AUTH_METHOD: 'access-token'
  # =================== END If Vault is used ======================
  # =================== If Vault is NOT used ==========================
  JF_AUTH_METHOD: "username-password"
  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
  DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
  # ==================== END If Vault is NOT used ======================

jobs:
  maven_release_and_publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}
    # Changed to permissions: 'write-all' for compatibility, flexibility, and ease of customization.
    # Please update to stricter permissions if your workflow has specific security requirements.
    permissions: 'write-all'
    steps:
      # ============= if Vault instead of GitHub Secrets is used ===================

      #      - name: Load Secrets from Vault
      #        id: secrets
      #        uses: hashicorp/vault-action@v3
      #        with:
      #          url: https://vault-kms.prod.datev.de/
      #          method: jwt
      #          caCertificate: ${{ vars.VAULT_CA_PROD_CERT }} # Provided globally by the admins
      #          role: ${{ vars.VAULT_ROLE || github.event.repository.name }}
      #          jwtGithubAudience: datev-vault
      #          path: github
      #          secrets: |
      #            artifactory/token/artifactory-ns-${{ vars.ARTIFACTORY_NAMESPACE }} access_token | ARTIFACTORY_TOKEN ;
      #            artifactory/token/artifactory-ns-${{ vars.ARTIFACTORY_NAMESPACE }} username | ARTIFACTORY_USERNAME ;
      #            kv/data/${{ vars.VAULT_DEPLOY_KEY_SELECTOR }} | DEPLOY_KEY ;

      # ============= END if Vault instead of GitHub Secrets is used ================

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ env.DEPLOY_KEY }}

      - name: Maven release
        id: maven-release
        uses: datevscm/progressive-workflows/actions/maven-release-and-publish-action@v1
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          default-bump: ${{ env.VERSION_BUMP }}
          auth-method: ${{ env.JF_AUTH_METHOD }}
          conventional-commits-enabled: true
          ARTIFACTORY_USERNAME: ${{ env.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_TOKEN: ${{ env.ARTIFACTORY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Emit event
        uses: datevscm/progressive-workflows/actions/emit-event@v1
        with:
          event_name: publish-success
          json_payload: |
            { "publish":
              {
                "version":"${{ steps.maven-release.outputs.release-version }}",
                "git_tag":"${{ steps.maven-release.outputs.release-version }}"
              }
            }
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
